fix IO redirection in acquire-reboot-lock

diff --git a/modules/debian-org/files/molly-guard/15-acquire-reboot-lock b/modules/debian-org/files/molly-guard/15-acquire-reboot-lock
--- a/modules/debian-org/files/molly-guard/15-acquire-reboot-lock
+++ b/modules/debian-org/files/molly-guard/15-acquire-reboot-lock
@@ -6,7 +6,7 @@ l=/var/run/reboot-lock
 exec 3> $l
 
 if ! flock --exclusive -w 0  3; then
-	echo 2>&1 "Cannot acquire reboot lock."
+	echo >&2 "Cannot acquire reboot lock."
 	exit 1
 fi
 echo "Reboot lock acquired."
