Print clearer problem report if setup-dchroot fails

diff --git a/modules/porterbox/files/setup-all-dchroots b/modules/porterbox/files/setup-all-dchroots
--- a/modules/porterbox/files/setup-all-dchroots
+++ b/modules/porterbox/files/setup-all-dchroots
@@ -67,7 +67,13 @@ err=0
 
 for a in $archs; do
     for s in `get_suites "$a"`; do
-        setup-dchroot -f -a "$a" "$s" || err=1
+        if ! setup-dchroot -f -a "$a" "$s"; then
+            err=1
+            echo >&2
+            echo >&2 "Error: setting up $s:$a dchroot failed."
+            echo >&2
+            echo >&2
+        fi
     done
 done
 
