Check pipe status

diff --git a/modules/postgres/files/backup_server/postgres-make-base-backups b/modules/postgres/files/backup_server/postgres-make-base-backups
--- a/modules/postgres/files/backup_server/postgres-make-base-backups
+++ b/modules/postgres/files/backup_server/postgres-make-base-backups
@@ -62,6 +62,10 @@ while read host port username  cluster version; do
 	trap "rm -f '$tmp'" EXIT
 
 	/usr/lib/postgresql/"$version"/bin/pg_basebackup --format=tar --pgdata=- --label="$label" --host="$host" --port="$port" --username="$username" --no-password $console | pigz > "$tmp"
+	if ! [ "${PIPESTATUS[0]}" -eq 0 ]; then
+		echo >&2 "pg_basebackup failed with exit code ${PIPESTATUS[0]}"
+		exit 1
+	fi
 	mv "$tmp" "$ROOTDIR/${host%%.*}/$target"
 done << EOF
 chopin.debian.org	5432	debian-backup		dak		9.1
