Revert "setup-dchroot: create /srv/chroot"
the point of the check is to make sure we have created /srv/chroot on a
suitable filesystem, as we don't want the scripts to run if we haven't
done all the filesystem setup yet

This reverts commit 47e806d785e3195f855584d0739abb0ee2682c27.

diff --git a/modules/schroot/files/setup-dchroot b/modules/schroot/files/setup-dchroot
--- a/modules/schroot/files/setup-dchroot
+++ b/modules/schroot/files/setup-dchroot
@@ -294,7 +294,7 @@ if [ -z "${builddir:-}" ]; then
     fi
   done
 fi
-[ -d "$basedir" ] || mkdir -p "$basedir"
+[ -d "$basedir" ] || die "Error: $basedir does not exist (or is not a directory)."
 [ -d "$builddir" ] || die "Error: $builddir does not exist (or is not a directory)."
 
 target="$basedir/$tuple.tar.gz"
